arch:
  - amd64
  - arm64
language: minimal
sudo: required
services:
  - docker
script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./build.sh "$TARGET" "$GIT_TAG" -p
  - ./build.sh "$TARGET" "master" -p
