name: GitHub Actions CI

on:
  push:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  buildx:
    strategy:
      fail-fast: false
      matrix:
        target:
          - java-gateway-ubuntu
          - proxy-mysql-ubuntu
          - proxy-sqlite3-ubuntu
          - server-pgsql-ubuntu
          - zabbix-appliance-alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Install latest Docker X version
        run: curl -fsSL https://raw.githubusercontent.com/pschmitt/ci-setup-docker-buildx/master/setup.sh | bash

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build target ${{ matrix.target }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: ./build.sh ${{ matrix.target }} -p
